[tool.poetry]
name = "minuteinbox"
description = "Unofficial python wrapper for minuteinbox.com"
documentation = "https://github.com/fedecalendino/minuteinbox/blob/main/README.md"
homepage = "https://github.com/fedecalendino/minuteinbox"
license = "MIT"
readme = "README.md"
version = "0.3.0"

authors = [
  "Fede Calendino <fede@calendino.com>",
]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
]
keywords = [
  "minuteinbox.com",
]
packages = [
  { include = "minuteinbox" },
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
coverage = "^7.0.0"
ddt = "^1.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
